name: 'C++ CI'

on:
  push:
    branches:
      - lab_1_a
      - feature/github_actions

jobs:
  build:
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
      
      - name: Download libraries
        run: sudo apt-get update && sudo apt-get install libboost-test-dev -y

      - name: Configure Cmake
        run: cmake -B build -S . ; cmake build -DPATCH_VERSION=${{ github.run_number }}

      - name: Build project
        run: cmake --build build ; cmake --build build --target test ; cmake --build build --target package
          
      - name: Upload Release Asset
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        shell: bash
        run: |
          gh release create v0.1.${{ github.run_number }} build/helloworld-0.1.${{ github.run_number }}-Linux.deb