name: 'C++ programming. Laboratory work 2'

on:
  push:
    branches:
      - lab_2_a
      - feature/github_actions

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    permissions: write-all

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Configure Cmake
        env:
          generator: ${{
            matrix.os == 'ubuntu-latest' && 'Unix Makefiles' ||
            matrix.os == 'windows-latest' && 'Visual Studio 17 2022'}}
          architecture: ${{
            matrix.os == 'windows-latest' && '-A x64'}}
        run: cmake -B build -S . -G "${generator}" ${architecture} 

      - name: Build project
        run: cmake --build build ; cmake --build build --target test ; cmake --build build --target package --config Release
          
      - name: Upload Release Asset
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        shell: bash
        run: |
          TAG=$(git describe --abbrev=0 --tags)
          if gh release view "${TAG}" > /dev/null 2>&1; 
          then gh release upload "${TAG}" bin/ip_reader-${TAG}-Linux.deb;
          else gh release create "${TAG}" bin/ip_reader-${TAG}-Linux.deb;
          fi